### ISSUE TITLE
Upside down doesn't handle escapes properly

### ISSUE THREAD

**Issue by Dhranios** [magiczocker10/magiczocker10.github.io#1]
Input:
`{
"test": "Test \"string\""
}`

Output:
`{
"test": "„\ᵷuᴉɹʇs„\ ʇsǝ⟘"
}`

Expected output:
`{
"test": "„ᵷuᴉɹʇs„ ʇsǝ⟘"
}`

**Comment by magiczocker10** [comment]
Issue should be fixed now
