### ISSUE TITLE
Upside down requires a space between colon and value quote

### ISSUE THREAD

**Issue by Dhranios** [magiczocker10/magiczocker10.github.io#2]
Works as expected:
`{
"test": "Test"
}`

Doesn't do anything:
`{
"test":"Test"
}`

**Comment by magiczocker10** [comment]
Should be fixed now.

**Comment by Dhranios** [comment]
Not fixed yet, same with #1; is the version used not live?

**Comment by magiczocker10** [comment]
Sorry about that. I forgot to deploy the changes.
