### ISSUE TITLE
Upside down: Bracket on last line conversion removes last bracket

### ISSUE THREAD

**Issue by Dhranios** [magiczocker10/magiczocker10.github.io#4]
```
{
"test": "test"}
```
turns into 
```
{
"test": "ʇsǝʇ"
```
note the lack of `}`
```
{"test": "test"
}
```
works fine

**Comment by magiczocker10** [comment]
Your json format looks different from what the script is intended for. I used the same formatting as vanilla minecraft to code the converter.

**Comment by Dhranios** [comment]
While not conventional, it is an accepted format.

**Comment by magiczocker10** [comment]
Your provided example now works too.
